services:
  db:
    image: postgres:16
    container_name: MobyParkPostgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: MobyParkDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  api:
    build:
      context: .
      dockerfile: backend/MobyPark-api/Dockerfile
    image: mobypark-api:dev

volumes:
  db_data: