name: .NET CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  DOTNET_VERSION: '9.0.x'
  SOLUTION: MobyPark_Project_2526.sln
  TEST_PROJECT: backend/MobyPark-api.tests/MobyPark-api.tests.csproj
  REGISTRY: ghcr.io
  IMAGE_NAME: floorengl/mobypark_project_2526/mobypark-api

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, x64, mobypark]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.SOLUTION }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION }}" -c Release --no-restore

      - name: Test
        run: dotnet test "${{ env.TEST_PROJECT }}" -c Release --no-build

  build-and-push-image:
    needs: build-and-test
    runs-on: [self-hosted, linux, x64, mobypark]

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -f backend/MobyPark-api/Dockerfile -t $IMAGE backend/MobyPark-api
          docker push $IMAGE


  deploy:
    needs: build-and-push-image
    runs-on: [self-hosted, linux, x64, mobypark]

    steps:
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy artifact
        env:
          IMAGE: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        run: |
          export MOBYPARK_API_IMAGE=$IMAGE
          docker compose down || true
          docker compose up -d
